<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <RootNamespace>Tetris</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!-- Gestion des dépendances NuGet -->
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Raylib-CsLo" Version="4.2.0.9" />
  </ItemGroup>

  <ItemGroup>
    <!-- Police -->
    <Content Include="font\*.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <!-- Fichiers JSON -->
    <Content Include="json\**\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <!-- Audio -->
    <Content Include="audio\*.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <!-- Music -->
    <Content Include="audio\*.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <!-- Images -->
    <Content Include="icon\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
