<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

    <!-- FOR RELEASE -->
    <OutputType>WinExe</OutputType>

    <!-- FOR DEBUGGING -->
    <!-- <OutputType>Exe</OutputType> -->

    <TargetFramework>net5.0</TargetFramework>
    <RootNamespace>Tetris</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!-- NuGet dependencies management -->
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Raylib-CsLo" Version="4.2.0.9" />
  </ItemGroup>

  <ItemGroup>
    <!-- Fonts -->
    <Content Include="font\*.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <!-- JSON files -->
    <Content Include="json\**\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <!-- Audio -->
    <Content Include="audio\*.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <!-- Music -->
    <Content Include="audio\*.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <!-- Images -->
    <Content Include="icon\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
